local:
  hosts:
    vm:
      ansible_host: 192.168.56.10
      ansible_ssh_private_key_file: ./ssh/id_ed25519
      ansible_user: vagrant
      ngrok_authtoken: "<your ngrok Authtoken>"

ngrok:
  hosts:
    vm:
      ansible_host: 0.tcp.sa.ngrok.io
      ansible_ssh_private_key_file: ./ssh/id_ed25519
      ansible_user: vagrant
      ansible_port: 12656